#!/usr/bin/env bash
# Copy the five live modules in, then run their tests.
#
# These modules have no Tauri dependency, so unlike the typecheck harness
# this actually *executes* their #[cfg(test)] suites. Copying (never
# symlinking — see tools/typecheck-harness/README.md) means the tests run
# against the real source, so a test cannot pass by testing a stale copy.
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC="$REPO/src-tauri/src"
HERE="$(cd "$(dirname "$0")" && pwd)"

for m in crypto group protocol secure_key storage; do
  if [ -L "$HERE/src/$m.rs" ]; then
    echo "FATAL: $HERE/src/$m.rs is a symlink — refusing." >&2
    echo "A harness wrote through a symlink here before and truncated the live tree." >&2
    exit 1
  fi
done

for m in crypto group protocol secure_key storage; do
  cp "$SRC/$m.rs" "$HERE/src/$m.rs"
done

# Regenerate `commands_generated.rs` from the live source.
#
# `ChatMessage` used to be hand-maintained in `src/commands.rs`, field for field
# — the only non-machine-copied file in a directory where everything else is
# copied on every run. It had no drift detector, and `storage.rs` compiles
# against that copy, so a field added to the real `ChatMessage` (see the 7-site
# checklist in CLAUDE.md) would desync silently while the storage tests kept
# passing. Extracting the real definition closes that.
#
# `ChatMessage` is a plain serde struct with no Tauri types, so the probe can
# compile it: pull in the `use serde::` line and the struct body. The AEAD
# helpers in `commands/util.rs` are still a hand-written mirror — that one is a
# deliberate, documented stub, because it returns `AppError` and pulling in the
# real module would drag the whole command layer behind it.
if [ -f "$SRC/commands/mod.rs" ]; then
  {
    echo '// GENERATED by tools/crypto-probe/sync.sh - do not edit by hand.'
    echo '// Extracted from src-tauri/src/commands/mod.rs on every run so the probe'
    echo '// compiles the REAL ChatMessage rather than a hand-maintained copy.'
    echo '#![allow(dead_code)]'
    grep -E '^use serde::' "$SRC/commands/mod.rs" || true
    awk '/^#\[derive\(.*Serialize.*Deserialize.*\)\]/{d=1} d{print} /^pub struct ChatMessage \{/{s=1} s&&/^\}/{exit}' \
      "$SRC/commands/mod.rs" | sed -n '/^#\[derive/,$p'
  } > "$HERE/src/commands_generated.rs"

  if ! grep -q 'pub struct ChatMessage' "$HERE/src/commands_generated.rs"; then
    echo "FATAL: failed to extract ChatMessage from $SRC/commands/mod.rs" >&2
    echo "The probe would compile against a stale copy. Aborting." >&2
    exit 1
  fi
fi

cd "$HERE"
cargo test --lib "$@"
