#!/usr/bin/env bash
# Copy the five live modules in, then run their tests.
#
# These modules have no Tauri dependency, so unlike the typecheck harness
# this actually *executes* their #[cfg(test)] suites. Copying (never
# symlinking — see tools/typecheck-harness/README.md) means the tests run
# against the real source, so a test cannot pass by testing a stale copy.
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC="$REPO/src-tauri/src"
HERE="$(cd "$(dirname "$0")" && pwd)"

for m in crypto group protocol secure_key storage; do
  if [ -L "$HERE/src/$m.rs" ]; then
    echo "FATAL: $HERE/src/$m.rs is a symlink — refusing." >&2
    echo "A harness wrote through a symlink here before and truncated the live tree." >&2
    exit 1
  fi
done

for m in crypto group protocol secure_key storage; do
  cp "$SRC/$m.rs" "$HERE/src/$m.rs"
done

# Regenerate `commands.rs` from the live source.
#
# `src/commands.rs` used to be a hand-maintained, field-for-field copy of
# `commands::ChatMessage` — in a directory where every other file is
# machine-copied, with no drift detector. Adding a field to `ChatMessage` (see
# the 7-site checklist in CLAUDE.md) would silently desync the copy while
# `storage.rs`'s tests kept passing against the wrong shape, because the copy is
# what those tests compile against.
#
# `ChatMessage` is a plain serde struct with no Tauri types, so the probe can
# compile the real definition: extract it plus its `use` lines into a shim.
if [ -f "$SRC/commands/mod.rs" ]; then
  {
    echo '// GENERATED by tools/crypto-probe/sync.sh — do not edit by hand.'
    echo '// Extracted from src-tauri/src/commands/mod.rs so the probe compiles the'
    echo '// real ChatMessage definition instead of a hand-maintained copy.'
    echo '#![allow(dead_code, unused_imports)]'
    grep -E '^use .*Serialize' "$SRC/commands/mod.rs" || true
    grep -E '^use serde::' "$SRC/commands/mod.rs" || true
    awk '/^pub struct ChatMessage \{/,/^\}/' "$SRC/commands/mod.rs"
  } > "$HERE/src/commands.rs"
fi

cd "$HERE"
cargo test --lib "$@"
