// GENERATED by tools/crypto-probe/sync.sh - do not edit by hand.
// Extracted from src-tauri/src/commands/mod.rs so the probe compiles the
// real ChatMessage definition instead of a hand-maintained copy.
#![allow(dead_code, unused_imports)]
use serde::{Deserialize, Serialize};
pub struct ChatMessage {
    pub id: String,
    pub content: String,
    pub direction: String,
    pub timestamp: u64,
    /// When this message was read (null = unread, only for received messages).
    pub read_at: Option<i64>,
    /// When this message was edited (null = never edited).
    pub edited_at: Option<i64>,
    /// Whether this message has been soft-deleted.
    pub deleted: bool,
    /// When this message self-destructs (null = never).
    pub expires_at: Option<i64>,
    /// Reactions on this message, as a map: reaction_emoji → [peer_key_hex, ...].
    #[serde(default)]
    pub reactions: std::collections::HashMap<String, Vec<String>>,
    /// Sender of this message (used for group messages — Ed25519 hex).
    /// Empty string for 1:1 messages (implicit from conversation).
    #[serde(default)]
    pub sender_peer_key_hex: String,
}
