#!/usr/bin/env bash
# Typecheck the whole M2M app without GTK.
#
# ## Why this exists
#
# `cargo check` in `src-tauri/` cannot build here: `glib-sys` / `gio-sys` /
# `gdk-sys` build scripts need GTK *development* packages (`.pc` files) that are
# not obtainable in this environment — only the GTK runtime is in the nix store.
# That means the app's own Rust code — 50 modules including the entire Tauri
# command layer — cannot be typechecked by cargo at all.
#
# This script builds a throwaway crate that compiles all of those modules against
# a stub `tauri` crate, so `cargo check` gives real answers about real code.
#
# ## Usage
#
#     ./check.sh && cargo check --offline --lib
#
# (or just `./check.sh --run`, which does both).
#
# !!! DANGER — NEVER SYMLINK THE LIVE SOURCES INTO HERE !!!
#
# An earlier rlib-based harness created symlinks from `src/*.rs` to the live
# `src-tauri/src/*.rs`. A later `sed ... >` redirect then wrote *through* the
# symlinks and truncated all 20 live source files to 0 bytes. They were
# recoverable only because nothing had been committed since. This script copies
# real files and refuses to run if it finds a symlink anywhere it is about to
# write. Do not reintroduce symlinks.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HARNESS="$REPO/tools/typecheck-harness"
BUILD="$HARNESS/build"
APP="$REPO/src-tauri/src"

# ── 0. Symlink guard ─────────────────────────────────────────────────────────
if find "$APP" -type l | grep -q .; then
  echo "FATAL: symlink found under $APP — refusing to run." >&2
  echo "A harness wrote through a symlink here before and truncated the tree." >&2
  exit 1
fi

# ── 1. Generate the harness manifest from the real one ───────────────────────
# Hand-maintaining a second dependency list guarantees it drifts: add a crate to
# src-tauri/Cargo.toml, forget the harness, and get a confusing "unresolved
# import" that looks like a code bug. So the list is *derived*.
#
# Everything is kept except the four GTK-coupled crates, which are replaced by
# the local stub. Versions are left exactly as the app pins them.
{
  cat <<'HEADER'
# GENERATED BY check.sh — DO NOT EDIT.
# Derived from src-tauri/Cargo.toml; see that file for the source of truth.
#
# `autobins` and friends are off because only `lib.rs` and the modules it
# declares are copied — `main.rs` is the binary entry point and the harness is
# a lib-only crate.

[package]
name = "m2m_harness"
version = "0.0.0"
edition = "2021"
autobins = false
autotests = false
autoexamples = false
autobenches = false

# Standalone. Without this, cargo refuses to build it because the harness lives
# inside the repo's directory tree and so appears to be a missing workspace
# member. An empty table keeps it out of the real workspace entirely, so the
# app's dependency graph and lockfile are never affected by harness crates.
[workspace]

[lib]
name = "m2m_lib"
path = "src/lib.rs"

[dependencies]
tauri = { path = "../tauri_stub" }
HEADER

  # Re-emit every non-GTK dependency line from the app manifest, dropping the
  # section headers and comments.
  sed -n '/^\[dependencies\]/,/^\[dev-dependencies\]/p' "$REPO/src-tauri/Cargo.toml" \
    | grep -E '^[a-z0-9_-]+ *=' \
    | grep -vE '^(tauri|tauri-build|tauri-plugin-[a-z]+) *='
} > "$HARNESS/Cargo.toml"

# ── 2. Fresh copy of the sources ─────────────────────────────────────────────
rm -rf "$BUILD"
mkdir -p "$BUILD/src"
cp -R "$APP/." "$BUILD/src/"
rm -f "$BUILD/src/main.rs"

# ── 3. Strip attribute macros ────────────────────────────────────────────────
# `#[tauri::command]`, `#[tauri::main]` and `#[tauri::mobile_entry_point]` are
# attribute (proc) macros. A plain crate cannot provide them, so the lines go.
find "$BUILD/src" -name '*.rs' -print0 | xargs -0 sed -i \
  -e '/^[[:space:]]*#\[tauri::command\]/d' \
  -e '/^[[:space:]]*#\[tauri::main\]/d' \
  -e '/#\[cfg_attr(mobile, tauri::mobile_entry_point)\]/d'

# ── 4. Point the plugin crates at the stub ───────────────────────────────────
# The real `tauri_plugin_*` crates depend on the real `tauri`; the stub exposes
# them as modules instead.
find "$BUILD/src" -name '*.rs' -print0 | xargs -0 sed -i \
  -e 's/\btauri_plugin_dialog\b/tauri::plugin_dialog/g' \
  -e 's/\btauri_plugin_notification\b/tauri::plugin_notification/g' \
  -e 's/\btauri_plugin_updater\b/tauri::plugin_updater/g'

# `include_bytes!("../icons/icon.png")` resolves outside `src/`.
mkdir -p "$BUILD/icons"
cp "$REPO/src-tauri/icons/icon.png" "$BUILD/icons/"

# ── 5. Resolve against the workspace lockfile ────────────────────────────────
# Without the real Cargo.lock, `--offline` resolution fails on crates that are
# in the local registry cache only under the versions the app pins.
cp "$REPO/Cargo.lock" "$BUILD/Cargo.lock"

# ── 6. Optionally check ──────────────────────────────────────────────────────
if [ "${1:-}" = "--run" ]; then
  cd "$BUILD"
  cargo check --offline --lib
fi

echo "check.sh: sources staged in $BUILD/src"
